H5N1_avian_hosts = ['Chicken', 'chicken', 'CHICKEN']
H5N1_bovine_hosts = ['Cattle', 'cattle']
H5N1_human_hosts = ['human']
H5N2_avian_hosts = ['chicken']
H5N2_swine_hosts = ["swine"]
H5N3_avian_hosts = ['Duck', 'duck', 'mallard', 'mallard duck']
H5N4_avian_hosts = ['mallard']
H5N5_avian_hosts = ['mallard', 'duck']
H5N6_avian_hosts = ['duck', 'Duck']
H5N6_swine_hosts = ['swine']
# Place holder for H5N6_human_hosts
H5N7_avian_hosts = ['duck', 'Duck', 'mallard', 'Mallard']
H5N8_avian_hosts = ['chicken']